### PR TITLE
Fix style issue and duplicated banners issue

### PR DESCRIPTION
**Pull request by edwardwang1105**
Hi Chris,

Your extension is very helpful for me but it doesn't work well in some websites. e.g. Solr.
Could you merge my request and update the extension.
solr

Thank you & best regards,
Edward

### CODE REVIEW

**Comment by chrishepner** [comment]
Hey Edward,

Thanks for the contribution! I'll merge this and release a new version to the Chrome Web Store shortly.

(If this hasn't been completed in a few days, message me- I'll likely have forgotten about it.)

**Comment by edwardwang1105** [comment]
Thank you, Chris. It's a great help.

**Comment by edwardwang1105** [comment]
@chrishepner Hi Chris,
It seems the new version hasn't been released to Chrome Web Store. Please have a check. Thank you.

**Comment by chrishepner** [comment]
Thanks for the reminder. I've submitted the new version and it should be live within the next 60 minutes:
https://chrome.google.com/webstore/detail/acekbdliodimhedjoaifioeppmfiokon/publish-delayed?hl=en-US&gl=US

**Comment by edwardwang1105** [comment]
@chrishepner There it is! Thank you Chris. But the following error occurs when I trying to install it.
Maybe you missed the image file.
error

**Comment by chrishepner** [comment]
This should be fixed! Thanks.

**Comment by edwardwang1105** [comment]
That works! Thank you!

**Pull request merged**
